Repository 7-final-project/queue, pull requests merged in 2025-01, with the labels that each got.

#5 대기 생성 기능 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/qring/queue/application/v1/res/QueueGetByIdResDTOV1.java
  src/main/java/com/qring/queue/application/v1/res/QueueGetTableResDTOV1.java
  src/main/java/com/qring/queue/application/v1/res/QueueInfoDTO.java
  src/main/java/com/qring/queue/application/v1/res/QueuePostResDTOV1.java
  src/main/java/com/qring/queue/application/v1/service/QueueServiceV1.java
  src/main/java/com/qring/queue/domain/model/QueueEntity.java
  src/main/java/com/qring/queue/domain/model/constraint/QueueStatus.java
  src/main/java/com/qring/queue/infrastructure/config/KafkaConsumerConfig.java
  src/main/java/com/qring/queue/infrastructure/config/RedisConfig.java
  src/main/java/com/qring/queue/infrastructure/repository/QueueRepository.java
  src/main/java/com/qring/queue/presentation/v1/controller/QueueControllerV1.java
  src/main/java/com/qring/queue/presentation/v1/req/PostQueueReqDTOV1.java
  src/main/resources/application-dev.yml
Labels: 🌐 API, ✨ Feature

#9 대기 서비스 생성 프로세스 구조 개선
  src/main/java/com/qring/queue/application/v1/res/QueueInfoDTOV1.java
  src/main/java/com/qring/queue/application/v1/res/QueuePostResDTOV1.java
  src/main/java/com/qring/queue/application/v1/service/QueueServiceV1.java
  src/main/java/com/qring/queue/application/v2/message/redis/RedisMessagePublisherV2.java
  src/main/java/com/qring/queue/application/v2/res/QueueGetResDTOV2.java
  src/main/java/com/qring/queue/application/v2/service/QueueServiceV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationCreateEventDTO.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageConsumerV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/redis/RedisMessagePublisherImplV2.java
  src/main/java/com/qring/queue/presentation/v1/controller/QueueControllerV1.java
  src/main/java/com/qring/queue/presentation/v2/controller/QueueControllerV2.java
Labels: 🌐 API, ✨ Feature, 🔨 Refactor

#15 대기 순번 알림 기능 구현
  docker-compose.yml
  src/main/java/com/qring/queue/application/v2/message/kafka/KafkaMessageProducerV2.java
  src/main/java/com/qring/queue/application/v2/message/redis/RedisKeyspaceListener.java
  src/main/java/com/qring/queue/application/v2/message/redis/RedisMessagePublisherV2.java
  src/main/java/com/qring/queue/application/v2/service/QueueServiceV2.java
  src/main/java/com/qring/queue/infrastructure/config/KafkaProducerConfig.java
  src/main/java/com/qring/queue/infrastructure/config/RedisListenerConfig.java
  src/main/java/com/qring/queue/infrastructure/docs/QueueControllerSwagger.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/QueueAlarmEventDTO.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageProducerImplV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/redis/RedisMessagePublisherImplV2.java
  src/main/java/com/qring/queue/presentation/v2/controller/QueueControllerV2.java
  src/main/resources/application-dev.yml
Labels: 🌐 API, ✨ Feature

#17 대기 서비스 예약 정보 + 대기 정보 이벤트 발행
  src/main/java/com/qring/queue/application/v2/message/kafka/KafkaMessageProducerV2.java
  src/main/java/com/qring/queue/application/v2/message/redis/RedisKeyspaceListener.java
  src/main/java/com/qring/queue/application/v2/message/redis/RedisMessagePublisherV2.java
  src/main/java/com/qring/queue/application/v2/res/QueueGetResDTOV2.java
  src/main/java/com/qring/queue/application/v2/service/QueueServiceV2.java
  src/main/java/com/qring/queue/infrastructure/config/RedisListenerConfig.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/QueueAlarmEventDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationAndQueueEventDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationCreateEventDTO.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationEventDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageConsumerV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageProducerImplV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/redis/RedisMessagePublisherImplV2.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature, 🔨 Refactor

#19 대기 서비스 수정
  src/main/java/com/qring/queue/application/v2/message/redis/RedisKeyspaceListener.java
  src/main/java/com/qring/queue/application/v2/message/redis/RedisMessagePublisherV2.java
  src/main/java/com/qring/queue/application/v2/service/QueueServiceV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationAndQueueEventDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationCreationEventDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationEventDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageConsumerV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/redis/RedisMessagePublisherImplV2.java
  src/main/resources/application-dev.yml
Labels: 🔨 Refactor

#25 메세지 서비스 관련 DTO 수정
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationAndQueueEventDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/ReservationEventDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/dto/UpdateReservationMessageDTOV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageConsumerV2.java
Labels: 🔨 Refactor

#27 대기 서비스 SAGA 패턴 적용
  src/main/java/com/qring/queue/application/v2/message/kafka/KafkaMessageProducerV2.java
  src/main/java/com/qring/queue/application/v2/service/QueueServiceV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageConsumerV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageProducerImplV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/redis/RedisMessagePublisherImplV2.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature

#31 운영환경 설정을 위한 YML 파일 구성 및 클래스 버전별 분류 제거
  src/main/java/com/qring/queue/application/messaging/kafka/KafkaMessageProducerV2.java
  src/main/java/com/qring/queue/application/messaging/redis/RedisMessagePublisherV2.java
  src/main/java/com/qring/queue/application/res/QueueGetResDTOV2.java
  src/main/java/com/qring/queue/application/service/QueueServiceV2.java
  src/main/java/com/qring/queue/application/v1/res/QueueGetByIdResDTOV1.java
  src/main/java/com/qring/queue/application/v1/res/QueueGetTableResDTOV1.java
  src/main/java/com/qring/queue/application/v1/res/QueueInfoDTOV1.java
  src/main/java/com/qring/queue/application/v1/res/QueuePostResDTOV1.java
  src/main/java/com/qring/queue/application/v1/service/QueueServiceV1.java
  src/main/java/com/qring/queue/infrastructure/config/KafkaConsumerConfigV1.java
  src/main/java/com/qring/queue/infrastructure/config/KafkaConsumerConfigV2.java
  src/main/java/com/qring/queue/infrastructure/docs/QueueControllerSwagger.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageConsumerV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/kafka/KafkaMessageProducerImplV2.java
  src/main/java/com/qring/queue/infrastructure/messaging/redis/RedisKeyspaceListener.java
  src/main/java/com/qring/queue/infrastructure/messaging/redis/RedisMessagePublisherImplV2.java
  src/main/java/com/qring/queue/presentation/QueueControllerV2.java
  src/main/java/com/qring/queue/presentation/v1/controller/QueueControllerV1.java
  src/main/java/com/qring/queue/presentation/v1/req/PostQueueReqDTOV1.java
  src/main/java/com/qring/queue/presentation/v1/req/PutQueueReqDTOV1.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/qring/queue/QueueApplicationTests.java
Labels: ⚙ Setting, 🔨 Refactor, 🚀 Deploy
